## Introduction

In [ ]:
'''
1. Pytorch Framework - Tensors datatypes
Tensors are similar to numpy arrays, tensors can run on gpus where as numpy arrays cannot run on gpus.
Tenors support Automatic Differentiation
'''

##Initalizaing a Tensor

In [1]:
import numpy as np
import torch

In [2]:
data = [[1,2],[3,4]]
#converting this to numpy array
np_array = np.array(data)
print(np_array.shape)
print(np_array)
print(type(np_array))

(2, 2)
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [3]:
torch_tensor = torch.Tensor(data)
print(torch_tensor.shape)
print(torch_tensor)
print(type(torch_tensor))

torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>


In [4]:
# Converting numpy array to tenor
x_tensor = torch.from_numpy(np_array)
print(x_tensor)

tensor([[1, 2],
        [3, 4]])


In [5]:
##Create a tensor of all ones similar to x_tensor
x_ones = torch.ones_like(x_tensor)
x_ones

tensor([[1, 1],
        [1, 1]])

In [6]:
##Create a random tensor similar to x_tensor
x_rand = torch.rand_like(x_tensor,dtype=torch.float) #np.float
x_rand

tensor([[0.2102, 0.2285],
        [0.8939, 0.5833]])

In [7]:
shape = (2,3,) #2x3x1

rand_tensor = torch.rand(shape) #np.random.rand
ones_tensor = torch.ones(shape) #np.ones
zeros_tensor = torch.zeros(shape) #np.zeros

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.4186, 0.5931, 0.5519],
        [0.6391, 0.7223, 0.8320]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
print(rand_tensor.shape)

torch.Size([2, 3])


In [9]:
tensor = torch.rand(3,4)

In [10]:
tensor.shape

torch.Size([3, 4])

In [11]:
tensor.dtype

torch.float32

In [12]:
tensor.device

device(type='cpu')

In [13]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
  pass

In [14]:
tensor.device

device(type='cuda', index=0)

In [16]:
tensor = torch.ones(4,4)

In [17]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
tensor[0] #First row of the tensor

tensor([1., 1., 1., 1.])

In [19]:
tensor[:,0]

tensor([1., 1., 1., 1.])

In [20]:
tensor[:,-1]

tensor([1., 1., 1., 1.])

In [21]:
## concatenating the tensor
tensor = torch.rand(4,4)
tensor

tensor([[0.3689, 0.6126, 0.9224, 0.6010],
        [0.3734, 0.1073, 0.0960, 0.2281],
        [0.3271, 0.4113, 0.1484, 0.2810],
        [0.9845, 0.9560, 0.0233, 0.6454]])

In [22]:
torch.cat([tensor,tensor,tensor],dim=1) #dim - dimension

tensor([[0.3689, 0.6126, 0.9224, 0.6010, 0.3689, 0.6126, 0.9224, 0.6010, 0.3689,
         0.6126, 0.9224, 0.6010],
        [0.3734, 0.1073, 0.0960, 0.2281, 0.3734, 0.1073, 0.0960, 0.2281, 0.3734,
         0.1073, 0.0960, 0.2281],
        [0.3271, 0.4113, 0.1484, 0.2810, 0.3271, 0.4113, 0.1484, 0.2810, 0.3271,
         0.4113, 0.1484, 0.2810],
        [0.9845, 0.9560, 0.0233, 0.6454, 0.9845, 0.9560, 0.0233, 0.6454, 0.9845,
         0.9560, 0.0233, 0.6454]])

In [23]:
## Arithemetic Operations
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)

y1 = t1 @ t2.T ##or
y2 = t1.matmul(t2.T)

In [24]:
y1

tensor([[0.3002, 0.0250],
        [0.8177, 0.0676]])

In [25]:
y2

tensor([[0.3002, 0.0250],
        [0.8177, 0.0676]])

In [26]:
## [2x2] and [2x2]
z1 = t1*t2

In [27]:
z1

tensor([[0.2237, 0.0766],
        [0.0499, 0.0178]])

In [28]:
z2 = t1.mul(t2) #matmul does matrix multiplication : mul does elementwise multiplication

In [29]:
t1

tensor([[0.2485, 0.2473],
        [0.6349, 0.7952]])

In [30]:
agg = t1.sum()

In [31]:
agg

tensor(1.9259)

In [32]:
agg.item()

1.9259133338928223

In [34]:
t1 = torch.ones(4,4)
t1[:,1] = 0
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [35]:
t1.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [36]:
x = np.array([[1,2],[3,4]])
tensor = torch.from_numpy(x) #convert it into tensor
y = tensor.numpy()#convert it to numpy array

In [38]:
type(x)

numpy.ndarray

In [39]:
type(tensor)

torch.Tensor

In [40]:
type(y)

numpy.ndarray